CREATE TABLE IF NOT EXISTS tokens (
    hash BYTEA PRIMARY KEY NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    scope TEXT NOT NULL,
    expiry TIMESTAMP(0) WITH TIME ZONE NOT NULL
);